# Generated by Django 2.2.27 on 2022-09-29 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20220927_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='properties',
            field=models.ManyToManyField(blank=True, to='core.Property'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Role'),
        ),
    ]
