# Generated by Django 2.2.27 on 2022-09-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20220929_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissionlog',
            old_name='initiated_by',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='permissionlog',
            name='type_of_change',
        ),
        migrations.AddField(
            model_name='permissionlog',
            name='type',
            field=models.CharField(choices=[('Role', 'Role'), ('Property', 'Property')], default='Role', max_length=300),
        ),
        migrations.AlterField(
            model_name='permissionlog',
            name='added_properties',
            field=models.ManyToManyField(blank=True, related_name='_permissionlog_added_properties_+', to='core.Property'),
        ),
        migrations.AlterField(
            model_name='permissionlog',
            name='deleted_properties',
            field=models.ManyToManyField(blank=True, related_name='_permissionlog_deleted_properties_+', to='core.Property'),
        ),
        migrations.AlterField(
            model_name='permissionlog',
            name='new_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Role'),
        ),
        migrations.AlterField(
            model_name='permissionlog',
            name='old_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Role'),
        ),
    ]
