# Generated by Django 2.2.27 on 2022-09-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20220929_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionlog',
            name='type',
            field=models.CharField(choices=[('Role', 'Role'), ('Property', 'Property')], max_length=300),
        ),
    ]
