# Generated by Django 2.2.27 on 2022-10-03 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20220929_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionlog',
            name='account_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_logs', to='manager.AccountUser'),
        ),
    ]
