# Generated by Django 2.2.27 on 2022-10-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20221003_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionlog',
            name='email',
            field=models.EmailField(default='dej@gamil.com', max_length=250),
        ),
    ]
