# Generated by Django 2.2.27 on 2022-10-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_permissionlog_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionlog',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
