# Generated by Django 2.2.27 on 2022-10-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20221003_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionlog',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Updated'), (2, 'DELETED')]),
        ),
        migrations.AlterField(
            model_name='permissionlog',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Role'), (1, 'Property')]),
        ),
    ]
