# Generated by Django 2.2.27 on 2022-10-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20221003_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionlog',
            name='source',
            field=models.CharField(choices=[('CREATED', 'User Created'), ('UPDATED', 'User Updated'), ('DELETED', 'User Deleted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='permissionlog',
            name='type',
            field=models.CharField(choices=[('Role', 'Role Changed'), ('Property', 'Property changed')], max_length=20),
        ),
    ]
